language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm
matrix:
  allow_failures:
  - php: hhvm
before_script: composer update --dev
script:
- php vendor/phpunit/phpunit/phpunit.php --configuration tools/phpunit
after_success:
- if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/bin/coveralls -v; fi
notifications: