language: php
env:
  global:
    - MEMCACHE_HOST=127.0.0.1
    - MEMCACHE_PORT=11211
services:
  - memcached
  - postgresql
  - mysql
php:
- 5.3
- 5.4
- 5.5
- 5.6
sudo: required
before_install:
install:
- mkdir /tmp/slapd
- cp docs/ldapstore.schema /tmp/slapd/
- slapd -f tests/slapd.conf -h ldap://localhost:1234 &
- pecl install pdo_mysql
- composer update --dev
- ldapadd -x -h localhost:1234 -D cn=admin,dc=example,dc=com -w secret -f tests/setup_store.ldif
before_script:
- psql -c 'create database oauth2server_test;' -U postgres
- psql -U postgres -d oauth2server_test <docs/store.sql
- mysql -e 'create database oauth2server_test;' -u travis
- mysql -u travis oauth2server_test <docs/store.sql
- echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
- php vendor/phpunit/phpunit/phpunit.php --configuration tools/phpunit
after_success:
- vendor/bin/test-reporter
- php vendor/bin/coveralls -v
addons:
  apt:
    packages:
    - ldap-utils
    - slapd
    - php5-ldap
  code_climate:
    repo_token: b7d516a1ddf338de68ccee9895de17e7d362a0b2923f61111ac4c446a0fab6b8
